### ISSUE TITLE
有个table疑问?

### ISSUE THREAD

**Issue by zhugexinxin** [xiongcaihu/cy-editor#1]
官方table，在td里三连击鼠标左键并复制再黏贴会异常
![image](https://user-images.githubusercontent.com/42615243/144718253-12fac744-8ca0-4c31-b17d-5925ed9ce443.png)
但是在您的编辑器里没发现异常，查看了代码，并未发现处理该问题代码，是我遗漏了吗？

**Comment by zhugexinxin** [comment]
我明白了，似乎找到了，三克油你的代码

**Comment by xiongcaihu** [comment]
ok
